/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/male/model.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Character(props) {
  const { nodes, materials } = useGLTF("models/male/model.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.64}>
        <primitive object={nodes.LeftFootCtrl} />
        <primitive object={nodes.RightFootCtrl} />
        <primitive object={nodes.HipsCtrl} />
        <skinnedMesh
          geometry={nodes.characterMedium.geometry}
          material={materials["skin.001"]}
          skeleton={nodes.characterMedium.skeleton}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/male/model.gltf");
